steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/eternal-lodge-484208-j6/dtu-mlops-dummy/dummy:latest',
    '-f',
    'Dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/eternal-lodge-484208-j6/dtu-mlops-dummy/dummy:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY